spring.application.name=javaApp

spring.datasource.url=jdbc:mysql://localhost:3306/campifydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

security.jwt.secret=secretoproyectointermodularcampify
security.jwt.issuer=campify
